version: 2

models:
  - name: bronze_abr
    description: "Modelo bronze com os dados brutos de abril de 2025, extraídos dos portais imobiliários."
    columns:
      - name: origem
        description: "Fonte do anúncio."
      - name: localizacao
        description: "Endereço bruto do imóvel."
      - name: preco
        description: "Preço informado no anúncio."
      - name: tipo
        description: "Tipo do imóvel (casa, apartamento, etc.)."
      - name: area
        description: "Área útil do imóvel em m²."
      - name: quartos
        description: "Quantidade de quartos."
      - name: banheiros
        description: "Quantidade de banheiros."
      - name: vagas
        description: "Vagas de garagem."
      - name: condo
        description: "Valor do condomínio (string)."
      - name: date_ref
        description: "Data de referência da coleta (ex: '2025-04')."

  - name: bronze_mai
    description: "Modelo bronze com os dados brutos de maio de 2025, extraídos dos portais imobiliários."
    columns:
      - name: origem
        description: Fonte do anúncio.
      - name: localizacao
        description: "Endereço bruto do imóvel."
      - name: preco
        description: "Preço informado no anúncio."
      - name: tipo
        description: "Tipo do imóvel (casa, apartamento, etc.)."
      - name: area
        description: "Área útil do imóvel em m²."
      - name: quartos
        description: Quantidade de quartos.
      - name: banheiros
        description: "Quantidade de banheiros."
      - name: vagas
        description: "Vagas de garagem."
      - name: condo
        description: "Valor do condomínio (string)."
      - name: date_ref
        description: "Data de referência da coleta (ex: '2025-05')."

  - name: bronze_jun
    description: "Modelo bronze com os dados brutos de junho de 2025, extraídos dos portais imobiliários."
    columns:
      - name: origem
        description: Fonte do anúncio.
      - name: localizacao
        description: "Endereço bruto do imóvel."
      - name: preco
        description: "Preço informado no anúncio."
      - name: tipo
        description: "Tipo do imóvel (casa, apartamento, etc.)."
      - name: area
        description: "Área útil do imóvel em m²."
      - name: quartos
        description: Quantidade de quartos.
      - name: banheiros
        description: "Quantidade de banheiros."
      - name: vagas
        description: "Vagas de garagem."
      - name: condo
        description: "Valor do condomínio (string)."
      - name: date_ref
        description: "Data de referência da coleta (ex: '2025-05')."