version: 2

models:
  - name: obt_imoveis
    description: "Tabela gold com os imóveis unificados, enriquecida com features geográficas e faixas de preço."
    columns:
      - name: id
        description: "Chave única gerada via hash dos dados do imóvel."
        tests:
          - unique
          - not_null
      - name: date_ref
        description: "Data de referência do dado."
      - name: tipo
        description: "Tipo de imóvel (ex: apartamento, casa, etc.)."
      - name: localizacao
        description: "Nome do bairro ou localidade do imóvel."
      - name: secretaria_regional
        description: "Agrupamento da localização por secretaria regional."
      - name: prox_orla
        description: "Indica se o imóvel está próximo à orla."
      - name: prox_centro
        description: "Indica se o imóvel está próximo ao centro."
      - name: faixa_preco
        description: "Faixa de preço categorizada."
      - name: area
        description: "Área do imóvel em m²."
      - name: quartos
        description: "Quantidade de quartos."
      - name: banheiros
        description: "Quantidade de banheiros."
      - name: vagas
        description: "Quantidade de vagas de garagem."
      - name: preco
        description: "Valor do imóvel."
      - name: condo
        description: "Valor do condomínio."
      - name: ingestion_timestamp
        description: "Timestamp de ingestão da linha."

  - name: mart_tipos
    description: "Mart com estatísticas agregadas por tipo de imóvel e mês de referência."
    columns:
      - name: tipo
        description: "Tipo de imóvel."
      - name: date_ref
        description: "Data de referência do dado."
      - name: qtd_imoveis
        description: "Quantidade total de imóveis do tipo no mês."
      - name: ate_200k
        description: "Contagem de imóveis com preço até R$ 200.000."
      - name: entre_200k_500k
        description: "Contagem de imóveis com preço entre R$ 200.001 e R$ 500.000."
      - name: entre_500k_1m
        description: "Contagem de imóveis com preço entre R$ 500.001 e R$ 1.000.000."
      - name: entre_1m_5m
        description: "Contagem de imóveis com preço entre R$ 1.000.001 e R$ 5.000.000."
      - name: acima_5m
        description: "Contagem de imóveis com preço acima de R$ 5.000.000."
      - name: preco_medio
        description: "Preço médio dos imóveis."
      - name: preco_m2_medio
        description: "Preço médio por m²."
      - name: preco_mediano
        description: "Mediana dos preços."
      - name: preco_m2_mediano
        description: "Mediana do preço por m²."
      - name: variacao_m2_pct
        description: "Variação percentual do m² em relação ao mês anterior."
      - name: ingestion_timestamp
        description: "Timestamp de ingestão da linha."

  - name: mart_localizacao
    description: "Mart de localização enriquecida, categorizando regiões, proximidade com centro e orla."
    columns:
      - name: id
        description: "Chave única do imóvel."
      - name: date_ref
        description: "Data de referência."
      - name: tipo
        description: "Tipo de imóvel."
      - name: localizacao
        description: "Localização do imóvel."
      - name: secretaria_regional
        description: "Código da secretaria regional associada à localização."
      - name: prox_orla
        description: "Flag indicando proximidade com a orla."
      - name: prox_centro
        description: "Flag indicando proximidade com o centro."
      - name: faixa_preco
        description: "Faixa categorizada de preço do imóvel."
      - name: area
        description: "Área útil do imóvel."
      - name: quartos
        description: "Número de quartos."
      - name: banheiros
        description: "Número de banheiros."
      - name: vagas
        description: "Número de vagas de garagem."
      - name: preco
        description: "Valor total do imóvel."
      - name: condo
        description: "Valor do condomínio."
      - name: ingestion_timestamp
        description: "Timestamp de ingestão."

