version: 2

models:
  - name: silver_abr
    description: "Camada silver de imóveis de abril/2025 com dados tratados e deduplicados"
    columns:
      - name: id
        description: "Chave única gerada por hash dos campos principais"
        tests:
          - unique
          - not_null

      - name: origem
        description: "Fonte do anúncio"
      - name: date_ref
        description: "Data de referência da coleta"
      - name: tipo
        description: "Tipo de imóvel (casa, apartamento etc.)"
      - name: localizacao
        description: "Bairro/localização do imóvel"
      - name: area
        description: "Área útil do imóvel em m²"
      - name: quartos
        description: "Número de quartos"
      - name: banheiros
        description: "Número de banheiros"
      - name: vagas
        description: "Número de vagas de garagem"
      - name: preco
        description: "Preço do imóvel"
      - name: condo
        description: "Valor do condomínio"
      - name: ingestion_timestamp
        description: "Timestamp de ingestão para auditoria"

  - name: silver_mai
    description: "Camada silver de imóveis de maio/2025 com dados tratados e deduplicados"
    columns: 
      - name: id
        description: "Chave única gerada por hash dos campos principais"
        tests:
          - unique
          - not_null
      - name: origem
        description: "Fonte do anúncio"
      - name: date_ref
        description: "Data de referência da coleta"
      - name: tipo
        description: "Tipo de imóvel (casa, apartamento etc.)"
      - name: localizacao
        description: "Bairro/localização do imóvel"
      - name: area
        description: "Área útil do imóvel em m²"
      - name: quartos
        description: "Número de quartos"
      - name: banheiros
        description: "Número de banheiros"
      - name: vagas
        description: "Número de vagas de garagem"
      - name: preco
        description: "Preço do imóvel"
      - name: condo
        description: "Valor do condomínio"
      - name: ingestion_timestamp
        description: "Timestamp de ingestão para auditoria"

  - name: silver_jun
    description: "Camada silver de imóveis de junho/2025 com dados tratados e deduplicados"
    columns: 
      - name: id
        description: "Chave única gerada por hash dos campos principais"
        tests:
          - unique
          - not_null
      - name: origem
        description: "Fonte do anúncio"
      - name: date_ref
        description: "Data de referência da coleta"
      - name: tipo
        description: "Tipo de imóvel (casa, apartamento etc.)"
      - name: localizacao
        description: "Bairro/localização do imóvel"
      - name: area
        description: "Área útil do imóvel em m²"
      - name: quartos
        description: "Número de quartos"
      - name: banheiros
        description: "Número de banheiros"
      - name: vagas
        description: "Número de vagas de garagem"
      - name: preco
        description: "Preço do imóvel"
      - name: condo
        description: "Valor do condomínio"
      - name: ingestion_timestamp
        description: "Timestamp de ingestão para auditoria"